INHERIT: base.yml
site_description: Technical documentation for pytabify in Python and Robot Framework
site_url: https://angel-valdezzz.github.io/pytabify/
docs_dir: docs/en
site_dir: site
edit_uri: edit/main/docs/en/
theme:
  language: en
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-night
      name: Dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-sunny
      name: Light mode
plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: false
      fallback_to_build_date: true
      locale: en
      type: datetime
nav:
  - Home: index.md
  - User guide:
      - Installation: getting-started/installation.md
      - Quick start: getting-started/quickstart.md
      - Python: examples/python.md
      - Robot Framework: examples/robot-framework.md
      - Troubleshooting: troubleshooting/common-errors.md
  - Keyword reference: keywords/index.html
  - API reference:
      - Creating tables: reference/creator.md
      - Saving tables: reference/saver.md
      - DataTable: reference/data-table.md
      - File formats: reference/file-formats.md
  - Development:
      - Architecture: internal/architecture.md
      - Extending formats: internal/extending-readers-writers.md
  - Visual examples: examples/visual.md
